language: node_js
node_js:
  - '12'
  - '11'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run build
  - yarn run lint
  - yarn run check
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: Rk0WpmpTK1zraXYIwFZKusDKpcsHj2iPxB+bTi06NtApRrd607wrMRasxIe3TJHUtH+7neGpUJ2I60KpzIhd0HSKSx8Ajx/Sh2pH8FQPaclNe3LPRxcVMoPlJ+HYrhEF3n66lT53sHhmknBBwKKIwmK/SiygPIetqeRHhDiWM75wht1oTYSrS+lgH331WbrScDz9qWcNPFExJ0ApigPrNphSsLn7k/1EBPjaxDIP1BcLdvDeh0q8wHScAZJYFQB0D4y+cin3Q6zbDm7yKmETSSM1LKxRtHkHGovbHN1HGtB+beH8SIjfi0/QxY1gQngdCG+sqtq0lZeHhQeQ3NwBWb7XGT8kxODsxWEW+adBhEBlLruZqn8i5L0sk2ZTIlP74LEGYze4gad3NzXDhYucUN0PdjzsqKa9IBc1otTLZpShfBhtHw1ZkfF5wDs5YtVRLgOyDXY5RXhG+UH1cAJbq1gZ23xap87vrxoztKRTe6oVT4B1Fv6UtSJzdSH7iLy1qJQQHX0EV3dpu9FwL/7pZxkVxKXGpCb+V6ug5hTxK+ROUA3e7BV6cUgsiUryO4W35CS0mDm3RqEXf3r91atg6t/nQTZXyR8ChtUADzaObDzELic+WdlyVA8FQ9yiNPxLxIQofc+WO+C9kHlZMhyfIXr1omcJE5s4bokJfR5gHRg=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 12
env:
  global:
    - secure: Gf/nzNcxVUoc8/l8O2AYhgG5aDMtqSxwnskmHTZpyVg+rYbrL0VZTnx6cKJ2ND2KKReNze3kyRL/VT8rooHJqYMsIh/Xf8s6x9PDkbSz65ARURHXqi3QuLheZ9PutIg2Qyoi6xH7ShdLXU84fcACHkvsfLW5dq4p19nPJoEuOTEoeHPaD9IkkJpfNyxSo4RKFK7rJ/uRA0Z2HrV0lNvu0aTlFHik3rbWjrsgpV8f/Ycl1lkWaONZHBfQuxKl4qWVJjV5MIZjwb1wPTcTHJt/1YBDdeny+QaaA1oBEzTLaO6ldwA81rVXpmnN9pgQBCTph3FHJmXzU719A2ZsVy4OGyfPAI3ttXf3DkvFls7LhfGrHDo3RBX2iYW62EJKwVwjbfvO/h+pvaFkyOtz5Adpz28erInZG75ggniNRuy3xqLQxH5Frc0ckON62OM+NlK6tdQbLu4ToHSDCUNEqlS+uvh5wtrAcr/71Vb8jJ9SHnfl04MJnqMeFofYe0h3fUo9g6RxutrHeAM6Yp0EeEiKSopxFBhcAO44gkByBcdcvoUgl2C6fQA6eg65F7nxIs4YmLfbtVGjTGM4NvALipKcdpEV/WPcwXC3TLAmazZAx1Sg7z1698aXe7tU5rxF77nYqZ1fII08K7oG+unPnvb3LywswNeKKCp4BOYjG7NK1yc=
notifications:
  slack:
    secure: XBbMLc34S4rhIOaQgX2SRX8KY9MLhkiY7xxdTYKd6EEYABEPy4tFmq/agywJksoZdTbxzhLjqKiTQGO6HWNHJ4iIH6jPUxO/2/nVJT5jscLzeCMxKPj4hrm8XRboXs2kJdLmutlmxJymjcQobzGedwTkpKrg09RyEcGLfl4AI9olSOzjLCKTzRQuVN56YisE22hCHAPLxJWHN4D+wNcu0R+wNI8drDf4NtAra0GLdqWTa79NDZ1dVun8Q2sFhaQuso1lzo1UtCZrNEumhfaVrAw2Q5RUWSkuo6ZeH2l3saw+DlDZSKIMhYEaZVIODeKfMjcNAKNuhmcqCjQsevULymuYkT3KKFOWN6nxDQJ1VWF52LoUVaygAxTiS5+m6m4C88vQyXj31r05I4FoPTwIsIyg3oUfKApAlxIkL9JHK0nR1G+74YShTk6ggqGiL+ZMBey1b3R1ATZY/gUvyxxm9dHhUoYd+7uFHBOMnsVe7553h6hwioTchUva5omz7LhQ9X6MUwo+WvVg/5dJ05Bc7kCrqbjI5nK37Uha3d7mjw2+AYFc/4PJA1NSVt0PZOSw7ZzYVxeokoAa04zXwZBH9EFc5a8urBGnnyRuntyR9fDYX+u/qAGD/6xzXzmHIbdsPnWCzAJW8GQ/88Iy2RwMaCxISPHq22cSrUv7st9b9eU=
